# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rai < Formula
  desc "React Architecture Intelligence launcher"
  homepage "https://github.com/pavp/react-architecture-intelligence"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pavp/react-architecture-intelligence/releases/download/v0.1.3/rai_0.1.3_darwin_amd64.tar.gz"
      sha256 "859268d96f9b1c0c98e45d34b03340261467c88c67c8e79684bc8a0d244159be"

      define_method(:install) do
        bin.install "rai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pavp/react-architecture-intelligence/releases/download/v0.1.3/rai_0.1.3_darwin_arm64.tar.gz"
      sha256 "498331787c9f1ca1c9cf5d73966009aaab5cb4ba654d19e90e1ba274348dcf6a"

      define_method(:install) do
        bin.install "rai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavp/react-architecture-intelligence/releases/download/v0.1.3/rai_0.1.3_linux_amd64.tar.gz"
      sha256 "f1b53cb1ad0e17478162666addc3d3a952fd744f68a413f8f5424c366b5e2753"
      define_method(:install) do
        bin.install "rai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavp/react-architecture-intelligence/releases/download/v0.1.3/rai_0.1.3_linux_arm64.tar.gz"
      sha256 "0ae33923d1f356322e8301dd4568967414fcb97de55f0657af5e4574d15101ac"
      define_method(:install) do
        bin.install "rai"
      end
    end
  end
end
