# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rai < Formula
  desc "React Architecture Intelligence launcher"
  homepage "https://github.com/pavp/react-architecture-intelligence"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pavp/react-architecture-intelligence/releases/download/v0.2.0/rai_0.2.0_darwin_amd64.tar.gz"
      sha256 "68d7e9f3c3fb81978fa3bc9fa256499f1699204f857184324b369d058eef685d"

      define_method(:install) do
        bin.install "rai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pavp/react-architecture-intelligence/releases/download/v0.2.0/rai_0.2.0_darwin_arm64.tar.gz"
      sha256 "187035e1f2c84a557856343561a6df4795b316b9f5f9afaa3a282f11e9d8ca5c"

      define_method(:install) do
        bin.install "rai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavp/react-architecture-intelligence/releases/download/v0.2.0/rai_0.2.0_linux_amd64.tar.gz"
      sha256 "11419c953ed972967e8f79b9ab37fc74a8a46c66b86bc2313bfa19d98edf25f0"
      define_method(:install) do
        bin.install "rai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavp/react-architecture-intelligence/releases/download/v0.2.0/rai_0.2.0_linux_arm64.tar.gz"
      sha256 "bee4398a2c85a6bc63d74242e162430c72119e40ff3b3b9cab8f0dc51c779eee"
      define_method(:install) do
        bin.install "rai"
      end
    end
  end
end
